spring.application.name=branch
work.rothe.branch.github.cache.maximum_size=10000
work.rothe.branch.github.cache.initial_size=5000
work.rothe.branch.github.cache.ttl-minutes=60
rothe.work.branch.github.connect_timeout=10000
rothe.work.branch.github.read_timeout=10000
work.rothe.branch.github.users_url=https://api.github.com/users/{userId}
work.rothe.branch.github.repos_url=https://api.github.com/users/{userId}/repos