spring.application.name: branch
spring.mvc.problemdetails.enabled: true

logging.level.work.rothe: DEBUG
logging.level.io.github.resilience4j: TRACE
logging.level.org.springframework.cache: TRACE

work.rothe.branch.github.connect_timeout: 10000
work.rothe.branch.github.read_timeout: 10000
work.rothe.branch.github.users_url: https://api.github.com/users/{userId}
work.rothe.branch.github.repos_url: https://api.github.com/users/{userId}/repos

spring.cache.cache-names: githubUser
spring.cache.caffeine.spec: initialCapacity=5000, maximumSize=10000, expireAfterWrite=60m, recordStats

resilience4j.retry:
  instances:
    githubClient:
      maxAttempts: 3
      waitDuration: 500ms
      enableExponentialBackoff: true
      exponentialBackoffMultiplier: 2
      retryExceptions:
        - work.rothe.branch.exception.EmptyGitHubResponseException
        - org.springframework.web.client.ResourceAccessException